# Color mapping configuration for LEGO element colors
# Based on the LEGO color table with element color IDs and their corresponding names and RGB values

color_mapping:
  1:
    name: "White 1"
    rgb: [0.9568627450980393, 0.9568627450980393, 0.9568627450980393]
  5:
    name: "Brick Yellow 5"
    rgb: [0.8, 0.7254901960784313, 0.5529411764705883]
  21:
    name: "Bright Red 21"
    rgb: [0.7058823529411765, 0.0, 0.0]
  23:
    name: "Bright Blue 23"
    rgb: [0.11764705882352941, 0.35294117647058826, 0.6588235294117647]
  24:
    name: "Bright Yellow 24"
    rgb: [0.9803921568627451, 0.7843137254901961, 0.0392156862745098]
  26:
    name: "Black 26"
    rgb: [0.0, 0.0, 0.0]
  28:
    name: "Dark Green 28"
    rgb: [0.0, 0.5215686274509804, 0.16862745098039217]
  37:
    name: "Bright green 37"
    rgb: [0.34509803921568627, 0.6705882352941176, 0.2549019607843137]
  38:
    name: "Dark Orange 38"
    rgb: [0.5686274509803921, 0.3137254901960784, 0.10980392156862745]
  106:
    name: "Bright orange 106"
    rgb: [0.8392156862745098, 0.4745098039215686, 0.13725490196078433]
  107:
    name: "Bright Bluish Green 107"
    rgb: [0.0, 0.596078431372549, 0.5803921568627451]
  119:
    name: "Bright Yel. Green 119"
    rgb: [0.6470588235294118, 0.792156862745098, 0.09411764705882353]
  124:
    name: "Bright Red. Violet 124"
    rgb: [0.5647058823529412, 0.12156862745098039, 0.4627450980392157]
  135:
    name: "Sand Blue 135"
    rgb: [0.4392156862745098, 0.5058823529411764, 0.6039215686274509]
  138:
    name: "Sand Yellow 138"
    rgb: [0.5372549019607843, 0.49019607843137253, 0.3843137254901961]
  140:
    name: "Earth blue 140"
    rgb: [0.09803921568627451, 0.19607843137254902, 0.35294117647058826]
  141:
    name: "Earth green 141"
    rgb: [0.0, 0.27058823529411763, 0.10196078431372549]
  151:
    name: "Sand Green 151"
    rgb: [0.4392156862745098, 0.5568627450980392, 0.48627450980392156]
  154:
    name: "New dark red 154"
    rgb: [0.4470588235294118, 0.0, 0.07058823529411765]
  191:
    name: "Flame Yellowish Orange 191"
    rgb: [0.9882352941176471, 0.6745098039215687, 0.0]
  192:
    name: "Reddish brown 192"
    rgb: [0.37254901960784315, 0.19215686274509805, 0.03529411764705882]
  194:
    name: "Med. Stone Grey 194"
    rgb: [0.5882352941176471, 0.5882352941176471, 0.5882352941176471]
  199:
    name: "Dark Stone Grey 199"
    rgb: [0.39215686274509803, 0.39215686274509803, 0.39215686274509803]
  221:
    name: "Bright purple 221"
    rgb: [0.7843137254901961, 0.3137254901960784, 0.6078431372549019]
  222:
    name: "Light purple 222"
    rgb: [1.0, 0.6196078431372549, 0.803921568627451]
  226:
    name: "Cool Yellow 226"
    rgb: [1.0, 0.9254901960784314, 0.4235294117647059]
  268:
    name: "Medium Lilac 268"
    rgb: [0.26666666666666666, 0.10196078431372549, 0.5686274509803921]
  297:
    name: "Warm Gold 297"
    rgb: [0.6862745098039216, 0.5215686274509804, 0.13333333333333333]
  308:
    name: "Dark Brown 308"
    rgb: [0.20784313725490197, 0.12941176470588237, 0.0]
  312:
    name: "Medium Nougat 312"
    rgb: [0.6666666666666666, 0.49019607843137253, 0.3333333333333333]
  315:
    name: "Silver Metallic 315"
    rgb: [0.5490196078431373, 0.5490196078431373, 0.5490196078431373]
  316:
    name: "Titanium Metallic 316"
    rgb: [0.28627450980392155, 0.27450980392156865, 0.26666666666666666]
  321:
    name: "Dark Azur 321"
    rgb: [0.27450980392156865, 0.6078431372549019, 0.7647058823529411]
  322:
    name: "Medium azur 322"
    rgb: [0.40784313725490196, 0.7647058823529411, 0.8862745098039215]
  324:
    name: "Medium lavender 324"
    rgb: [0.6039215686274509, 0.4627450980392157, 0.6823529411764706]
  330:
    name: "Olive Green 330"
    rgb: [0.5450980392156862, 0.5176470588235295, 0.30980392156862746]

# Default color for unknown IDs
default:
  name: "UNKNOWN"
  rgb: [0.5, 0.5, 0.5] # Gray for unknown colors
